site_name: 2020_5EI_Team3
nav:
     - 'Business Model Canvas': 'Business Model Canvas.pdf'
     - 'index': 'index.md'
     - 'Project Charter': 'Project Charter.md'
    
theme:
    name: readthedocs

use_directory_urls: true
